version: '3.8'

services:
  mongod:
    image: mongo
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
    volumes:
      - /usr/local/mongodb/db:/data/db
  app:
    depends_on:
      - mongod
    build: ./
    restart: unless-stopped
    env_file: .env
    ports:
      - 3000:$PORT
    stdin_open: true
    tty: true